### PR TITLE
Add client for fixed access tokens; fix some serialization issues

### PR DESCRIPTION
**Pull request by kodamasama**

### CODE REVIEW

**Comment by djinnet** [comment]
can you explain the purpose of the picartoFixedClient? 
I have noticed that you have only added a default header which has the same functional as PicartoAuthticatedClient's default header with two small change.
The token and the String.Format. 
Wouldn't it be a better idea to change PicartoAuthticatedClient instead of make a new client? 
I approve the change in the UserData.cs and the change in GetFollowing function.

**Comment by kodamasama** [comment]
That might be a better way to do it. I'm not the most familiar with OAuth, but I assumed the headers already in place in the PicartoAuthenticatedClient would still be needed if using something besides the Persistent Access Token.

Thanks for writing this, by the way. Saved me so much time yesterday getting my little prototype going.

**Comment by djinnet** [comment]
The default header in PicartoAuthticatedClient is actually just a placeholder, since I didn't test the oauth yet. 

if you could change the header in PicartoAuthticatedClient, so it has the same header as in the fixed client plus remove PicartoFixedClient and pull request it again. I'll approved it right away after read it through. 👍 

(also you are welcome! I hope this wrapper is going to save a lots of programming hours on your part. Good luck with your prototype. :) )

**Review by djinnet — CHANGES_REQUESTED** [review]
change default header in PicartoAuthticatedClient to the same header in PicartoFixedClient. 
Remove PicartoFixedClient, since we don't want to have too many clients.

**Comment by kodamasama** [comment]
Done!

**Review by djinnet — APPROVED** [review]
It looks good. Hopefully it'll merge without any problems. I'll update the nuget package in the weekend or hopefully on friday.

**Pull request merged**
